title: <p align="center"> Chris Tran </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vikrant-Deshmukh/">LinkedIn</a> |
  <a href="https://github.com/vikrant-Deshmukh">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Data Science  at School of Information, University of Arizona.
  <br><br>
  I am currently a Data Analyst & Strategy Deployment  Intern at Genentech with a focus on NLP, Tableau Dashboards.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
